
- name: dewpt
  state_topic: "weatherstation/data"
  value_template: "{{ value_json.dewptf }}"
  unit_of_measurement: ""
- name: humidity
  state_topic: "weatherstation/data"
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: "%"
- name: precipRate
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: precipTotal
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: pressure
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: solarRadiation
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: stationID
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: temp
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: uv
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: windChill
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: winddir
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: windDirectionName
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: windGust
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""
- name: windSpeed
  state_topic: "weatherstation/data"
  value_template: "{{ value_json. }}"
  unit_of_measurement: ""


indoorhumidity
baromin
rtfreq
dewptf
windchillf
dailyrainin
weeklyrainin
tempf
softwaretype
windgustmph
rainin
solarradiation
UV
humidity
winddir
windspeedmph
dateutc
realtime
ID
monthlyrainin
yearlyrainin
indoortempf
