# configuration.yaml


sensor:
  - platform: mqtt
    name: "PWS ITAMASI1"
    state_topic: "WundergroundUpdateReceiverIDIKISSZ2"
    json_attributes_topic: "WundergroundUpdateReceiverIDIKISSZ2"
    value_template: "{{ value_json.tempf }}"
    force_update: true

weather:
  - platform: mqtt
    name: "Current Conditions"
    condition_topic: "weather/data"
    temperature_topic: "weather/data"
    humidity_topic: "weather/data"
    pressure_topic: "weather/data"
    wind_speed_topic: "weather/data"
    wind_bearing_topic: "weather/data"
    forecast_topic: "weather/forecast"
    forecast_template: "{{ value_json.forecast }}"
    condition_template: "{{ value_json.weather }}"
    temperature_unit: "F"
    humidity_unit: "%"
    pressure_unit: "inHg"
    wind_unit: "mph"

  - platform: openweathermap
    api_key: YOUR_API_KEY
    name: My Weather Forecast
    latitude: 37.7749
    longitude: -122.4194
    mode: daily
