# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: PWS to MQTT dispatcher addon
version: "0.1.19"
slug: pwsmqttdispatcher
description: Push weather station (PWS) data to MQTT
url: "https://github.com/peterzen/haas-pws-mqtt-addon/tree/main/pwsmqttdispatcher"
arch:
  - amd64
init: false
startup: application
options:
  pws_ip: "127.0.0.1"
  mqtt_topic: "pwsmqttdispatcher"
  mqtt_client_id: "pwsmqttdispatcher"
  fetch_interval: "60"
  debug_enabled: false
schema:
  pws_ip: "str"
  mqtt_topic: "str"
  mqtt_client_id: "str?"
  fetch_interval: "int"
  debug_enabled: "bool"
image: "docker.io/peterzen/pwsmqttdispatcher"
host_network: false
services:
  - mqtt:want
