name: "Publish"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to GH Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ${{ matrix.arch }}
        uses: home-assistant/builder@2025.02.0
        with:
          args: |
            --addon \
            --${{ matrix.arch }} \
            --target /data/pwsmqttdispatcher \
            --image "${{ matrix.arch }}-pwsmqttdispatcher" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"
