name: "Publish"

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GH Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@2023.12.0
        with:
          args: |
            --all \
            --target /data/pwsmqttdispatcher \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"
