name: "Test"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Test build
        uses: home-assistant/builder@2023.12.0
        with:
          args: |
            --test \
            --all \
            --target /data/pwsmqttdispatcher \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
