name: "Test"

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@2024.01.0
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --addon \
            --target /data/pwsmqttdispatcher \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
